'use strict';

var HTMLReport = require('../lib/jasmine-html-report-builder');
var fs = require('fs');
var fse = require('fs-extra');
var path = require('path');
var moment = require('moment');

function createFilePaths(target) {
    if (!fs.existsSync(target)) {
        console.log('Target junit directory does not exist: ' + __dirname + '/' + target);
        return [];
    }
    var files = fs.readdirSync(target);
    var filePaths = [];
    for (var i = 0; i < files.length; i++) {
        //var filePath = path.join(__dirname, '/', target, '/', files[i]); // Used to specify just files in dir
        var filePath = path.join(target, '/', files[i]);
        filePaths.push(filePath);
    }
    return filePaths;
}

function getDateString() {
    return moment().format('DD/MM/YYYY HH:mm');
}

module.exports = function(grunt) {
    // Load grunt tasks automatically
    require('load-grunt-tasks')(grunt);

    grunt.registerTask('genReport', function() {
        // Define fileSets for junit tests
        var fileSets = ['/Users/Anto/Documents/testOutput/result/junitFiles/chrome', '/Users/Anto/Documents/testOutput/result/junitFiles/safari'];
        var screenshotsDirs = ['/Users/Anto/Documents/testOutput/screenshots', '/Users/Anto/Documents/testOutput/screenshots/chrome', '/Users/Anto/Documents/testOutput/screenshots/safari'];
        var userDefinedDirsOverviewPage = [{ src: '/Users/Anto/Documents/testOutput/combined' }];
        var userDefinedButtonsOverviewPage = [{ onClickLocation: 'combined', buttonText: 'Unit Test Results' }];
        var userDefinedDirsChromeV53 = [{ src: '/Users/Anto/Documents/testOutput/chromeV53_UTRs' }];
        var userDefinedButtonsChromeV53 = [{ onClickLocation: 'chromeV53_UTRs', buttonText: 'Chrome Unit Test Results' }];
        var userDefinedDirsSafariV9_1 = [{ src: '/Users/Anto/Documents/testOutput/safariV9_1_UTRs' }];
        var userDefinedButtonsSafariV9_1 = [{ onClickLocation: 'safariV9_1_UTRs', buttonText: 'Safari Unit Test Results' }];
        // Note that you can create specific buttons and directories for each browser and also for the overview page if required
        var config = {
            overviewTitle: 'Overview - Test Results - ' + getDateString(),
            baseOutputPath: path.join(__dirname, '/results'),
            overviewScreenshotsDir: screenshotsDirs[0],
            includeSpecsInOverview: true,
            force: false,
            addSummaryDetails: [{
                tag: 'Testing Application: ',
                value: 'Super Awesome App'
            }, {
                tag: 'Test Generated By:',
                value: 'Tim Timmington'
            }], // Adds info defined here to the summary for the overview page
            userDefinedDirs: userDefinedDirsOverviewPage,
            userDefinedButtons: userDefinedButtonsOverviewPage,
            browsersConfig: [{
                reportTitle: 'Chrome - ' + getDateString(),
                browserName: 'Chrome-v53.0', // Used for folders etc
                specFiles: createFilePaths(fileSets[0]), // Send array of absolute paths to files from chrome folder
                screenshotsDir: screenshotsDirs[1],
                addSummaryDetails: [{
                    tag: 'Testing Application: ',
                    value: 'Super Awesome App'
                }, {
                    tag: 'Test Generated By:',
                    value: 'Tim Timmington'
                }], // The above 'addSummaryDetails' adds info defined here to the summary for the browser page
                userDefinedDirs: userDefinedDirsChromeV53,
                userDefinedButtons: userDefinedButtonsChromeV53
            }, {
                reportTitle: 'Safari - ' + getDateString(),
                browserName: 'Safari-v9.1', // Used for folders etc
                specFiles: createFilePaths(fileSets[1]), // Send array of absolute paths to files from chrome folder
                screenshotsDir: screenshotsDirs[2],
                addSummaryDetails: [{
                    tag: 'Testing Application: ',
                    value: 'Super Awesome App'
                }, {
                    tag: 'Test Generated By:',
                    value: 'Tim Timmington'
                }], // The above 'addSummaryDetails' adds info defined here to the summary for the browser page
                userDefinedDirs: userDefinedDirsSafariV9_1,
                userDefinedButtons: userDefinedButtonsSafariV9_1
            }]
        };

        // Generate report with this config
        new HTMLReport().from(config);
    });

    grunt.registerTask('clean', function() {
        var oldResults = path.join(__dirname, 'results');
        if (fs.existsSync(oldResults)) {
            try {
                fse.emptyDirSync(oldResults);
            } catch (err) {
                console.log('Error enptying old results directory');
                throw err;
            }

            try {
                fse.rmdirSync(oldResults);
            } catch (err) {
                console.log('Failed to delete old result directory');
                throw err;
            }
        }
    });

    grunt.registerTask('newResults', ['clean', 'genReport']);
    grunt.registerTask('default', ['newResults']);
};